<a href="https://colab.research.google.com/github/sameerk7552/Python_ML_AWS/blob/main/Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

filter

  1.array[Expression]
  2.array[array>2] || filter with mask



In [1]:
#filter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)

[ 90 200]


In [2]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr !=6]
print(arr_f)

[10 20 30  3  2]


In [3]:
# example and opr 10 se 20 between

import numpy as np
arr = np.array([10,20,30,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)


[15 18]


In [4]:
#Fancy indexing

import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_f = arr[[0,2]]# 0 index value , 2 index value
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]


In [7]:
# where
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_w = np.where(arr>9,"True","False")
print(arr_w)

[ 10  20   3   4  90 100]
['True' 'True' 'False' 'False' 'True' 'True']


In [10]:
# question 10 20 -> *2 | +2
import numpy as np
arr = np. array([10,20,3,4,90,100])
arr_w= np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)

[ 12  22   5   6  92 102]


In [15]:
# adding data and removing data

# concatenate using 1D
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

#concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

# concatenate using 2D
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2),axis=1) # for row 0, for column 1 but in case of sorting it  get reversed

print(arr1_arr2)


[10 20 30  1  2  3]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [17]:
# v stack -> vertically join | row-wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [18]:
# h stack -> horizontal join | column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)


[10 20 30 40 50 60]
