<a href="https://colab.research.google.com/github/sameerk7552/Python_ML_AWS/blob/main/Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

filter

  1.array[Expression]
  2.array[array>2] || filter with mask



In [ ]:
#filter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)

[ 90 200]


In [ ]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr !=6]
print(arr_f)

[10 20 30  3  2]


In [ ]:
# example and opr 10 se 20 between

import numpy as np
arr = np.array([10,20,30,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)


[15 18]


In [ ]:
#Fancy indexing

import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_f = arr[[0,2]]# 0 index value , 2 index value
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]


In [ ]:
# where
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_w = np.where(arr>9,"True","False")
print(arr_w)

[ 10  20   3   4  90 100]
['True' 'True' 'False' 'False' 'True' 'True']


In [ ]:
# question 10 20 -> *2 | +2
import numpy as np
arr = np. array([10,20,3,4,90,100])
arr_w= np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)

[ 12  22   5   6  92 102]


In [ ]:
# adding data and removing data

# concatenate using 1D
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

#concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

# concatenate using 2D
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2),axis=1) # for row 0, for column 1 but in case of sorting it  get reversed

print(arr1_arr2)


[10 20 30  1  2  3]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [ ]:
# v stack -> vertically join | row-wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
# h stack -> horizontal join | column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)


[10 20 30 40 50 60]


In [ ]:
# for 2d v stack
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[7,8,9]])
result = np.vstack((arr1,arr2))
print(result)

# for h stack
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[40,50,60],[70,80,90]])
result = np.hstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[10 20 30 40 50 60]
 [40 50 60 70 80 90]]


In [ ]:
# statical function

import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr)) # sum
print(np.min(arr))#min
print(np.max(arr))# max
print(np.mean(arr))# mean
print(np.median(arr)) #median


# np.sum(a) -> Sum of all elements
# np.mean(a) -> Average = Sum of elements / Number of elements
# np.median(a) -> Middle value after sorting
# np.min(a) -> Smallest value in array
# np.max(a) -> Largest value in array
# np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
# np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
# np.prod(a) -> Multiplication of all elements
# np.cumsum(a) -> Cumulative (running) sum
# np.cumprod(a) -> Cumulative (running) product
# np.argmin(a) -> Index position of minimum value
# np.argmax(a) -> Index position of maximum value
# np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
# np.unique(a) -> Returns unique values only -> Removes duplicates
# np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
# np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
# np.ptp(a) -> Range = Max - Min
# np.any(a) -> True if at least one value is True

30
2
10
6.0
6.0


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("Array =", a)

print("Sum =", np.sum(a))
print("Mean =", np.mean(a))
print("Median =", np.median(a))
print("Min =", np.min(a))
print("Max =", np.max(a))

print("Variance =", np.var(a))
print("Standard Deviation =", np.std(a))

print("Product =", np.prod(a))

print("Cumulative Sum =", np.cumsum(a))
print("Cumulative Product =", np.cumprod(a))

print("Index of Min =", np.argmin(a))
print("Index of Max =", np.argmax(a))

print("Absolute Value =", np.abs([-10, -20, 30]))

b = np.array([10, 20, 20, 30, 30, 40])
print("Unique Values =", np.unique(b))

print("50th Percentile =", np.percentile(a, 50))
print("0.5 Quantile =", np.quantile(a, 0.5))

print("Range (Max-Min) =", np.ptp(a))

c = np.array([False, False, True, False])
print("Any True? =", np.any(c))
print("All True? =", np.all(c))

Array = [10 20 30 40 50]
Sum = 150
Mean = 30.0
Median = 30.0
Min = 10
Max = 50
Variance = 200.0
Standard Deviation = 14.142135623730951
Product = 12000000
Cumulative Sum = [ 10  30  60 100 150]
Cumulative Product = [      10      200     6000   240000 12000000]
Index of Min = 0
Index of Max = 4
Absolute Value = [10 20 30]
Unique Values = [10 20 30 40]
50th Percentile = 30.0
0.5 Quantile = 30.0
Range (Max-Min) = 40
Any True? = True
All True? = False


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(np.sort(a))          # Sort array
print(np.flip(a))          # Reverse array
print(np.sqrt(a))          # Square root
print(np.square(a))        # Square
print(np.power(a, 2))      # Power
print(np.log(a))           # Natural log
print(np.exp(a))           # e^x

print(np.sin(a))           # Sine
print(np.cos(a))           # Cosine
print(np.tan(a))           # Tangent

print(np.ceil([1.2, 2.5, 3.1]))   # Round up
print(np.floor([1.2, 2.5, 3.9]))  # Round down
print(np.round([1.2, 2.5, 3.7]))  # Round nearest

print(np.count_nonzero(a)) # Count non-zero values
print(np.where(a > 25))    # Index where condition is True

print(np.clip(a, 15, 45))  # Limit values between 15 and 45

[10 20 30 40 50]
[50 40 30 20 10]
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[ 100  400  900 1600 2500]
[ 100  400  900 1600 2500]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
[2. 3. 4.]
[1. 2. 3.]
[1. 2. 4.]
5
(array([2, 3, 4]),)
[15 20 30 40 45]


Handling missing values

In [ ]:
# handling missing values
import numpy as np
arr = np.array([10,20,np.nan,40])
print(arr)
#isnan
print(np.isnan(arr))

# update nan by number

new_arr = np.nan_to_num(arr,nan=100)
print(new_arr)

[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]


In [ ]:
# Questions:-

# Print the complete dataset
# Find the shape of the array.
# Find the number of dimensions.
# Find the total number of elements.
# Print only Restaurant IDs.
# Print 2021 sales data.
# Print 2024 sales data
# Find the maximum sales value
# Find the minimum sales value.
# Find total sales of all restaurants in 2021.
# Find average sales in 2024.
# Find total sales of each restaurant.
# Find average sales of each restaurant.



In [42]:
# Data Structure : [restaurant_id, 2021, 2022, 2023, 2024]

import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],   # Beijing Bites
    [3, 200000, 230000, 260000, 300000],   # Pizza Hub
    [4, 180000, 210000, 240000, 270000],   # Burger Point
    [5, 160000, 185000, 205000, 230000]    # Chai Point
])

# 1. Print complete dataset
print("1 --> Complete dataset :\n", sales_data)

# 2. Shape of array
print("2 --> Shape of Array :", sales_data.shape)

# 3. Number of dimensions
print("3 --> Number of Dimensions :", sales_data.ndim)

# 4. Total number of elements
print("4 --> Total number of Elements :", sales_data.size)

# 5. Restaurant IDs
print("5 --> Restaurant IDs :\n", sales_data[:, 0])

# 6. 2021 sales data
print("6 --> 2021 sales data :\n", sales_data[:, 1])

# 7. 2024 sales data
print("7 --> 2024 sales data :\n", sales_data[:, -1])

# 8. Maximum sales value
print("8 --> Max sales Value :", np.max(sales_data[:, 1:]))

# 9. Minimum sales value
print("9 --> Min sales Value :", np.min(sales_data[:, 1:]))

# 10. Total sales in 2021
print("10 --> Total sales in 2021 :", np.sum(sales_data[:, 1]))

# 11. Average sales in 2024
print("11 --> Avg sales in 2024 :", np.average(sales_data[:, -1]))

# 12. Total sales of each restaurant
print("12 --> Total sales of each restaurant :\n",
      np.sum(sales_data[:, 1:], axis=1))

# 13. Average sales of each restaurant
print("13 --> Avg sales of each restaurant :\n",
      np.average(sales_data[:, 1:], axis=1))

1 --> Complete dataset :
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
2 --> Shape of Array : (5, 5)
3 --> Number of Dimensions : 2
4 --> Total number of Elements : 25
5 --> Restaurant IDs :
 [1 2 3 4 5]
6 --> 2021 sales data :
 [150000 120000 200000 180000 160000]
7 --> 2024 sales data :
 [250000 190000 300000 270000 230000]
8 --> Max sales Value : 300000
9 --> Min sales Value : 120000
10 --> Total sales in 2021 : 810000
11 --> Avg sales in 2024 : 248000.0
12 --> Total sales of each restaurant :
 [800000 610000 990000 900000 780000]
13 --> Avg sales of each restaurant :
 [200000. 152500. 247500. 225000. 195000.]
