<a href="https://colab.research.google.com/github/sameerk7552/Python_ML_AWS/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Numpy
import numpy as np
# 1d
l = [10,20,30,40]
l*2

[10, 20, 30, 40, 10, 20, 30, 40]

In [5]:
#power of numpy
arr = np.array(l)
arr*3

array([ 30,  60,  90, 120])

In [7]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[-1])

[1 2 3 4]
1
4


In [11]:
import numpy as np
# check type
l = [10,20,30,40]
print(l)
print(type(l))

arr = np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [12]:
#change values
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)

# numpy
arr = np.array(l)
arr[0]= 200
arr[-1]= 280
print(arr)

[100, 20, 30, 150]
[200  20  30 280]


In [16]:
# value add = 2
import numpy as np
l = [10,20,30,40]
# print(l+2) # addition not acceptable with list

arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [22]:
import numpy as np

arr = np.arange(9)  # 0 to 8
print(arr)

arr = np.arange(1, 7, 2)  # start=1, stop=7, step=2
print(arr)

[0 1 2 3 4 5 6 7 8]
[1 3 5]


In [18]:
for i in range(7):
  print(i)

0
1
2
3
4
5
6


In [23]:
# simple 2D example
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]
