<a href="https://colab.research.google.com/github/sameerk7552/Python_ML_AWS/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy | list
import numpy as np
import time

start= time.time()
sum1=0
for i in range(100000):
    sum1+= i*2
end = time.time()
#for list
print("for list : ",sum1,end-start)


for list :  9999900000 0.01621270179748535


In [ ]:
#for numpy | array(array works on every element)
start1=time.time()
sum2=0
arr = np.arange(100000)*2
sum2=arr.sum()
end1=time.time()
print("for array : ",sum2,end1-start1)


for array :  9999900000 0.0032377243041992188


In [ ]:
import time as t
print(t.time())

1781921198.9451218


In [ ]:
#zeros

import numpy as np
#array 1D
arr=np.zeros(5)
print(arr)


arr2=np.zeros(5)+7  # it shows 7 by the use of zeros
print(arr2)

[0. 0. 0. 0. 0.]
[7. 7. 7. 7. 7.]


In [ ]:
#array 2D
arr1=np.zeros((2,3)) #2rows and 3 columns
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones

import numpy as np
#array 1D
arr=np.ones(5)
print(arr)


[1. 1. 1. 1. 1.]


In [ ]:
#array 2D
arr1=np.ones((2,3)) #2rows and 3 columns
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#full

import numpy as np
#array1D
arr=np.full((5),7)   #full((5),7) -->  5 times 7
print(arr)

#array2D
arr1=np.full((2,3),5)
print(arr1)

[7 7 7 7 7]
[[5 5 5]
 [5 5 5]]


In [ ]:
#random number

import numpy as np
print(np.random.randint(1,10))

8


In [ ]:
# array opr on zeros | ones | full

import numpy as np

arr = np.zeros(5)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float

[0. 0. 0. 0. 0.]
(5,)
1
5
float64


In [ ]:
# 2d
print("2d zeros start")

arr1 = np.zeros((3, 2))

print(arr1)
print(arr1.shape)   # (3, 2)
print(arr1.ndim)    # 2
print(arr1.size)    # 6
print(arr1.dtype)   # float


2d zeros start
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


In [ ]:
# array opr on zeros | ones | full

import numpy as np

arr = np.ones(5)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float

# 2d
print("2d ones start")

arr1 = np.ones((3, 2))

print(arr1)
print(arr1.shape)   # (3, 2)
print(arr1.ndim)    # 2
print(arr1.size)    # 6
print(arr1.dtype)   # float


[1. 1. 1. 1. 1.]
(5,)
1
5
float64
2d ones start
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)
2
6
float64


In [ ]:
# array opr on zeros | ones | full

import numpy as np

arr = np.full((5),8)

print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # int

# 2d
print("2d full start")

arr1 = np.full((3, 2),8)

print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

[8 8 8 8 8]
(5,)
1
5
int64
2d full start
[[8 8]
 [8 8]
 [8 8]]
(3, 2)
2
6
int64


ARRAY RESHAPING


In [ ]:


#1D array

import numpy as np
arr=np.arange(6)
print(arr)

#2D array
import numpy as np
arr1=np.arange(1,13).reshape(3,4)
print(arr1)

#another approach
arr2=arr.reshape(2,3) #2rowa and 3 columns
print(arr2)

[0 1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 1 2]
 [3 4 5]]


In [ ]:
#flatten (convert to 1D)

import numpy as np
#2D
arr=np.arange(6)
arr1=arr.reshape(2,3)
print(arr1)

#flatten
arr_new=arr1.flatten()
arr_new[0]=100
print(arr1)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [ ]:
#ravel(convert to 1D)

import numpy as np
#2D
arr=np.arange(6).reshape(2,3)
print(arr)

#ravel
arr_new1=arr.ravel()
arr_new1[0]=200
print(arr)

[[0 1 2]
 [3 4 5]]
[[200   1   2]
 [  3   4   5]]


In [ ]:
#transpose

import numpy as np
arr=np.arange(6).reshape(2,3)
print(arr)

print(np.transpose(arr))

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[2])
print(arr[0:4]) # slicing
print(arr[-1])
print(arr[:1])
print(arr[0:3:2]) #start from 0 to 3 and jump 1
print(arr[::2]) # jump by one
print(arr[::-1]) #reverse

#questionn print 4 and 5
print(arr[-2:])

3
[1 2 3 4]
5
[1]
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [28]:
# for loop on numpy
#1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
for i in arr:
  print(i)
# 2d
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
  for j in i:
    for k in j:
      print(k)


[10 20 30 40]
10
20
30
40
1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
# for 2d
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for row in arr:
    print(row)

[1 2 3]
[4 5 6]


In [26]:
#for 3d
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for matrix in arr:
    print(matrix)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [12]:
import numpy as np
arrn= np.array([[10,20],[30,40],[50,60]])
print(arr)
print(arr[[]])

[[1 2 3]
 [4 5 6]]
[]


In [13]:
import numpy as np

# Data
arr = np.array([
    [2453, 75, 183975],
    [5795, 99, 573705],
    [4100, 36, 147600],
    [7526, 86, 647236],
    [9528, 45, 428760],
    [10788, 17, 183396]
])

countries = [
    "Australia",
    "Canada",
    "France",
    "Germany",
    "United Kingdom",
    "United States"
]

print("Country\t\tUnits Sold\tPrice\tRevenue")
for i in range(len(countries)):
    print(f"{countries[i]:15} {arr[i][0]:10} {arr[i][1]:5} {arr[i][2]:10}")

Country		Units Sold	Price	Revenue
Australia             2453    75     183975
Canada                5795    99     573705
France                4100    36     147600
Germany               7526    86     647236
United Kingdom        9528    45     428760
United States        10788    17     183396


In [14]:
import numpy as np

arr = np.array([
    [2453, 75, 183975],
    [5795, 99, 573705],
    [4100, 36, 147600],
    [7526, 86, 647236],
    [9528, 45, 428760],
    [10788, 17, 183396]
])

# Orange (first row, first two columns)
print(arr[0, 0:2])

# Green (rows France & Germany, all columns)
print(arr[2:4, :])

# Orange (last two revenue values)
print(arr[4:6, 2])

[2453   75]
[[  4100     36 147600]
 [  7526     86 647236]]
[428760 183396]


In [27]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0

[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


SORTING

In [36]:
import numpy as np
arr = np.array([10,35,40,7,15,20])
print(arr)
print(np.sort(arr)) # ascending
print(np.sort(arr)[::-1]) #decending

#2d
arr1 = arr.reshape(2,3)
print(arr1)
print(np.sort(arr1,axis=0))#default rows

[10 35 40  7 15 20]
[ 7 10 15 20 35 40]
[40 35 20 15 10  7]
[[10 35 40]
 [ 7 15 20]]
[[ 7 15 20]
 [10 35 40]]


In [37]:
#filter id '
import numpy as np
arr = np.array([10,20,30,40])
print(arr[arr>30])


[40]


In [38]:
#where
import numpy as np
arr = np.array([10,20,30,40])
print(np.where(arr>20,"true","false"))

# arr > 20 -> double | same print
print(np.where(arr>20,))


['false' 'false' 'true' 'true']
